language: go

dist: trusty

go:
  - 1.7.1

install:
  - # Do nothing. This is needed to prevent default instal action "go get -t -v ./..." from happening here.

script:
  - go build -v

branches:
  only:
    - master

notifications:
  email: true
    - firmament-dev@camsas.org

os:
  - linux
