// Code generated by protoc-gen-go.
// source: poseidonstats.proto
// DO NOT EDIT!

/*
Package stats is a generated protocol buffer package.

It is generated from these files:
	poseidonstats.proto

It has these top-level messages:
	NodeStats
	NodeStatsResponse
	PodStats
	PodStatsResponse
*/
package stats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeStats struct {
	Hostname       string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	CpuAllocatable uint64 `protobuf:"varint,2,opt,name=cpu_allocatable,json=cpuAllocatable" json:"cpu_allocatable,omitempty"`
	CpuCapacity    uint64 `protobuf:"varint,3,opt,name=cpu_capacity,json=cpuCapacity" json:"cpu_capacity,omitempty"`
	CpuReservation uint64 `protobuf:"varint,4,opt,name=cpu_reservation,json=cpuReservation" json:"cpu_reservation,omitempty"`
	CpuUtilization uint64 `protobuf:"varint,5,opt,name=cpu_utilization,json=cpuUtilization" json:"cpu_utilization,omitempty"`
	MemAllocatable uint64 `protobuf:"varint,6,opt,name=mem_allocatable,json=memAllocatable" json:"mem_allocatable,omitempty"`
	MemCapacity    uint64 `protobuf:"varint,7,opt,name=mem_capacity,json=memCapacity" json:"mem_capacity,omitempty"`
	MemReservation uint64 `protobuf:"varint,8,opt,name=mem_reservation,json=memReservation" json:"mem_reservation,omitempty"`
	MemUtilization uint64 `protobuf:"varint,9,opt,name=mem_utilization,json=memUtilization" json:"mem_utilization,omitempty"`
}

func (m *NodeStats) Reset()                    { *m = NodeStats{} }
func (m *NodeStats) String() string            { return proto.CompactTextString(m) }
func (*NodeStats) ProtoMessage()               {}
func (*NodeStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeStats) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NodeStats) GetCpuAllocatable() uint64 {
	if m != nil {
		return m.CpuAllocatable
	}
	return 0
}

func (m *NodeStats) GetCpuCapacity() uint64 {
	if m != nil {
		return m.CpuCapacity
	}
	return 0
}

func (m *NodeStats) GetCpuReservation() uint64 {
	if m != nil {
		return m.CpuReservation
	}
	return 0
}

func (m *NodeStats) GetCpuUtilization() uint64 {
	if m != nil {
		return m.CpuUtilization
	}
	return 0
}

func (m *NodeStats) GetMemAllocatable() uint64 {
	if m != nil {
		return m.MemAllocatable
	}
	return 0
}

func (m *NodeStats) GetMemCapacity() uint64 {
	if m != nil {
		return m.MemCapacity
	}
	return 0
}

func (m *NodeStats) GetMemReservation() uint64 {
	if m != nil {
		return m.MemReservation
	}
	return 0
}

func (m *NodeStats) GetMemUtilization() uint64 {
	if m != nil {
		return m.MemUtilization
	}
	return 0
}

type NodeStatsResponse struct {
}

func (m *NodeStatsResponse) Reset()                    { *m = NodeStatsResponse{} }
func (m *NodeStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeStatsResponse) ProtoMessage()               {}
func (*NodeStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PodStats struct {
	Name                string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace           string  `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	CpuLimit            uint64  `protobuf:"varint,3,opt,name=cpu_limit,json=cpuLimit" json:"cpu_limit,omitempty"`
	CpuRequest          uint64  `protobuf:"varint,4,opt,name=cpu_request,json=cpuRequest" json:"cpu_request,omitempty"`
	CpuUsage            uint64  `protobuf:"varint,5,opt,name=cpu_usage,json=cpuUsage" json:"cpu_usage,omitempty"`
	MemLimit            uint64  `protobuf:"varint,6,opt,name=mem_limit,json=memLimit" json:"mem_limit,omitempty"`
	MemRequest          uint64  `protobuf:"varint,7,opt,name=mem_request,json=memRequest" json:"mem_request,omitempty"`
	MemUsage            uint64  `protobuf:"varint,8,opt,name=mem_usage,json=memUsage" json:"mem_usage,omitempty"`
	MemWorkingSet       uint64  `protobuf:"varint,9,opt,name=mem_working_set,json=memWorkingSet" json:"mem_working_set,omitempty"`
	MemPageFaults       uint64  `protobuf:"varint,10,opt,name=mem_page_faults,json=memPageFaults" json:"mem_page_faults,omitempty"`
	MemPageFaultsRate   float64 `protobuf:"fixed64,11,opt,name=mem_page_faults_rate,json=memPageFaultsRate" json:"mem_page_faults_rate,omitempty"`
	MajorPageFaults     uint64  `protobuf:"varint,12,opt,name=major_page_faults,json=majorPageFaults" json:"major_page_faults,omitempty"`
	MajorPageFaultsRate float64 `protobuf:"fixed64,13,opt,name=major_page_faults_rate,json=majorPageFaultsRate" json:"major_page_faults_rate,omitempty"`
	NetRx               uint64  `protobuf:"varint,14,opt,name=net_rx,json=netRx" json:"net_rx,omitempty"`
	NetRxErrors         uint64  `protobuf:"varint,15,opt,name=net_rx_errors,json=netRxErrors" json:"net_rx_errors,omitempty"`
	NetRxErrorsRate     float64 `protobuf:"fixed64,16,opt,name=net_rx_errors_rate,json=netRxErrorsRate" json:"net_rx_errors_rate,omitempty"`
	NetRxRate           float64 `protobuf:"fixed64,17,opt,name=net_rx_rate,json=netRxRate" json:"net_rx_rate,omitempty"`
	NetTx               uint64  `protobuf:"varint,18,opt,name=net_tx,json=netTx" json:"net_tx,omitempty"`
	NetTxErrors         uint64  `protobuf:"varint,19,opt,name=net_tx_errors,json=netTxErrors" json:"net_tx_errors,omitempty"`
	NetTxErrorsRate     float64 `protobuf:"fixed64,20,opt,name=net_tx_errors_rate,json=netTxErrorsRate" json:"net_tx_errors_rate,omitempty"`
	NetTxRate           float64 `protobuf:"fixed64,21,opt,name=net_tx_rate,json=netTxRate" json:"net_tx_rate,omitempty"`
}

func (m *PodStats) Reset()                    { *m = PodStats{} }
func (m *PodStats) String() string            { return proto.CompactTextString(m) }
func (*PodStats) ProtoMessage()               {}
func (*PodStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PodStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodStats) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodStats) GetCpuLimit() uint64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *PodStats) GetCpuRequest() uint64 {
	if m != nil {
		return m.CpuRequest
	}
	return 0
}

func (m *PodStats) GetCpuUsage() uint64 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *PodStats) GetMemLimit() uint64 {
	if m != nil {
		return m.MemLimit
	}
	return 0
}

func (m *PodStats) GetMemRequest() uint64 {
	if m != nil {
		return m.MemRequest
	}
	return 0
}

func (m *PodStats) GetMemUsage() uint64 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *PodStats) GetMemWorkingSet() uint64 {
	if m != nil {
		return m.MemWorkingSet
	}
	return 0
}

func (m *PodStats) GetMemPageFaults() uint64 {
	if m != nil {
		return m.MemPageFaults
	}
	return 0
}

func (m *PodStats) GetMemPageFaultsRate() float64 {
	if m != nil {
		return m.MemPageFaultsRate
	}
	return 0
}

func (m *PodStats) GetMajorPageFaults() uint64 {
	if m != nil {
		return m.MajorPageFaults
	}
	return 0
}

func (m *PodStats) GetMajorPageFaultsRate() float64 {
	if m != nil {
		return m.MajorPageFaultsRate
	}
	return 0
}

func (m *PodStats) GetNetRx() uint64 {
	if m != nil {
		return m.NetRx
	}
	return 0
}

func (m *PodStats) GetNetRxErrors() uint64 {
	if m != nil {
		return m.NetRxErrors
	}
	return 0
}

func (m *PodStats) GetNetRxErrorsRate() float64 {
	if m != nil {
		return m.NetRxErrorsRate
	}
	return 0
}

func (m *PodStats) GetNetRxRate() float64 {
	if m != nil {
		return m.NetRxRate
	}
	return 0
}

func (m *PodStats) GetNetTx() uint64 {
	if m != nil {
		return m.NetTx
	}
	return 0
}

func (m *PodStats) GetNetTxErrors() uint64 {
	if m != nil {
		return m.NetTxErrors
	}
	return 0
}

func (m *PodStats) GetNetTxErrorsRate() float64 {
	if m != nil {
		return m.NetTxErrorsRate
	}
	return 0
}

func (m *PodStats) GetNetTxRate() float64 {
	if m != nil {
		return m.NetTxRate
	}
	return 0
}

type PodStatsResponse struct {
}

func (m *PodStatsResponse) Reset()                    { *m = PodStatsResponse{} }
func (m *PodStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PodStatsResponse) ProtoMessage()               {}
func (*PodStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*NodeStats)(nil), "stats.NodeStats")
	proto.RegisterType((*NodeStatsResponse)(nil), "stats.NodeStatsResponse")
	proto.RegisterType((*PodStats)(nil), "stats.PodStats")
	proto.RegisterType((*PodStatsResponse)(nil), "stats.PodStatsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PoseidonStats service

type PoseidonStatsClient interface {
	ReceiveNodeStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceiveNodeStatsClient, error)
	ReceivePodStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceivePodStatsClient, error)
}

type poseidonStatsClient struct {
	cc *grpc.ClientConn
}

func NewPoseidonStatsClient(cc *grpc.ClientConn) PoseidonStatsClient {
	return &poseidonStatsClient{cc}
}

func (c *poseidonStatsClient) ReceiveNodeStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceiveNodeStatsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PoseidonStats_serviceDesc.Streams[0], c.cc, "/stats.PoseidonStats/ReceiveNodeStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &poseidonStatsReceiveNodeStatsClient{stream}
	return x, nil
}

type PoseidonStats_ReceiveNodeStatsClient interface {
	Send(*NodeStats) error
	Recv() (*NodeStatsResponse, error)
	grpc.ClientStream
}

type poseidonStatsReceiveNodeStatsClient struct {
	grpc.ClientStream
}

func (x *poseidonStatsReceiveNodeStatsClient) Send(m *NodeStats) error {
	return x.ClientStream.SendMsg(m)
}

func (x *poseidonStatsReceiveNodeStatsClient) Recv() (*NodeStatsResponse, error) {
	m := new(NodeStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *poseidonStatsClient) ReceivePodStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceivePodStatsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PoseidonStats_serviceDesc.Streams[1], c.cc, "/stats.PoseidonStats/ReceivePodStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &poseidonStatsReceivePodStatsClient{stream}
	return x, nil
}

type PoseidonStats_ReceivePodStatsClient interface {
	Send(*PodStats) error
	Recv() (*PodStatsResponse, error)
	grpc.ClientStream
}

type poseidonStatsReceivePodStatsClient struct {
	grpc.ClientStream
}

func (x *poseidonStatsReceivePodStatsClient) Send(m *PodStats) error {
	return x.ClientStream.SendMsg(m)
}

func (x *poseidonStatsReceivePodStatsClient) Recv() (*PodStatsResponse, error) {
	m := new(PodStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PoseidonStats service

type PoseidonStatsServer interface {
	ReceiveNodeStats(PoseidonStats_ReceiveNodeStatsServer) error
	ReceivePodStats(PoseidonStats_ReceivePodStatsServer) error
}

func RegisterPoseidonStatsServer(s *grpc.Server, srv PoseidonStatsServer) {
	s.RegisterService(&_PoseidonStats_serviceDesc, srv)
}

func _PoseidonStats_ReceiveNodeStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoseidonStatsServer).ReceiveNodeStats(&poseidonStatsReceiveNodeStatsServer{stream})
}

type PoseidonStats_ReceiveNodeStatsServer interface {
	Send(*NodeStatsResponse) error
	Recv() (*NodeStats, error)
	grpc.ServerStream
}

type poseidonStatsReceiveNodeStatsServer struct {
	grpc.ServerStream
}

func (x *poseidonStatsReceiveNodeStatsServer) Send(m *NodeStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *poseidonStatsReceiveNodeStatsServer) Recv() (*NodeStats, error) {
	m := new(NodeStats)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PoseidonStats_ReceivePodStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoseidonStatsServer).ReceivePodStats(&poseidonStatsReceivePodStatsServer{stream})
}

type PoseidonStats_ReceivePodStatsServer interface {
	Send(*PodStatsResponse) error
	Recv() (*PodStats, error)
	grpc.ServerStream
}

type poseidonStatsReceivePodStatsServer struct {
	grpc.ServerStream
}

func (x *poseidonStatsReceivePodStatsServer) Send(m *PodStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *poseidonStatsReceivePodStatsServer) Recv() (*PodStats, error) {
	m := new(PodStats)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PoseidonStats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.PoseidonStats",
	HandlerType: (*PoseidonStatsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveNodeStats",
			Handler:       _PoseidonStats_ReceiveNodeStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceivePodStats",
			Handler:       _PoseidonStats_ReceivePodStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "poseidonstats.proto",
}

func init() { proto.RegisterFile("poseidonstats.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xc9, 0x58, 0x47, 0x72, 0xba, 0x2e, 0xad, 0xbb, 0x41, 0x34, 0x10, 0x8c, 0x5e, 0x40,
	0x05, 0xd2, 0x40, 0xec, 0x09, 0x26, 0xfe, 0x5c, 0x21, 0x34, 0x65, 0x9d, 0xb8, 0x8c, 0xbc, 0xec,
	0x50, 0x02, 0x71, 0x1c, 0x62, 0x67, 0x0c, 0x9e, 0x84, 0xf7, 0x83, 0x07, 0x41, 0x3e, 0x4e, 0xdc,
	0x24, 0x70, 0xb5, 0xf9, 0xf3, 0xef, 0x7c, 0xfe, 0xfa, 0xc9, 0x31, 0xcc, 0x4b, 0xa9, 0x30, 0xbb,
	0x92, 0x85, 0xd2, 0x5c, 0xab, 0xe3, 0xb2, 0x92, 0x5a, 0xb2, 0x11, 0x2d, 0x16, 0xbf, 0xb7, 0x20,
	0xf8, 0x20, 0xaf, 0xf0, 0xdc, 0xac, 0xd8, 0x21, 0xf8, 0x9f, 0xa5, 0xd2, 0x05, 0x17, 0x18, 0x79,
	0x47, 0xde, 0x32, 0x88, 0xdd, 0x9a, 0x3d, 0x85, 0x30, 0x2d, 0xeb, 0x84, 0xe7, 0xb9, 0x4c, 0xb9,
	0xe6, 0x97, 0x39, 0x46, 0x5b, 0x47, 0xde, 0x72, 0x3b, 0xde, 0x4b, 0xcb, 0xfa, 0x74, 0xa3, 0xb2,
	0xc7, 0xb0, 0x6b, 0xc0, 0x94, 0x97, 0x3c, 0xcd, 0xf4, 0x8f, 0xe8, 0x36, 0x51, 0xe3, 0xb4, 0xac,
	0x5f, 0x37, 0x52, 0xeb, 0x55, 0xa1, 0xc2, 0xea, 0x9a, 0xeb, 0x4c, 0x16, 0xd1, 0xb6, 0xf3, 0x8a,
	0x37, 0x6a, 0x0b, 0xd6, 0x3a, 0xcb, 0xb3, 0x9f, 0x16, 0x1c, 0x39, 0xf0, 0x62, 0xa3, 0x1a, 0x50,
	0xa0, 0xe8, 0xa5, 0xdb, 0xb1, 0xa0, 0x40, 0x31, 0x48, 0x67, 0x40, 0x97, 0xee, 0x8e, 0x4d, 0x27,
	0x50, 0x74, 0xd3, 0x19, 0xa4, 0x9b, 0xce, 0x77, 0x5e, 0x83, 0x74, 0x06, 0xec, 0xa6, 0x0b, 0x1c,
	0xd8, 0x49, 0xb7, 0x98, 0xc3, 0xcc, 0x95, 0x1c, 0xa3, 0x2a, 0x65, 0xa1, 0x70, 0xf1, 0x67, 0x04,
	0xfe, 0x99, 0xbc, 0xb2, 0xcd, 0x33, 0xd8, 0xee, 0xb4, 0x4e, 0xff, 0xb3, 0x07, 0x10, 0x98, 0xbf,
	0xaa, 0xe4, 0xa9, 0xed, 0x3a, 0x88, 0x37, 0x02, 0xbb, 0x0f, 0x81, 0xa9, 0x26, 0xcf, 0x44, 0xa6,
	0x9b, 0x8e, 0xfd, 0xb4, 0xac, 0xdf, 0x9b, 0x35, 0x7b, 0x04, 0x63, 0x5b, 0xf0, 0xb7, 0x1a, 0x95,
	0x6e, 0xca, 0x05, 0x2a, 0x97, 0x94, 0x76, 0xba, 0x56, 0x7c, 0x8d, 0x4d, 0xa5, 0x66, 0xfa, 0xc2,
	0xac, 0xcd, 0xa6, 0xf9, 0x5d, 0xd6, 0xda, 0xd6, 0xe8, 0x0b, 0x14, 0xce, 0xda, 0xb6, 0x63, 0xad,
	0x6d, 0x7f, 0x40, 0xcd, 0x38, 0x6b, 0x6a, 0x85, 0xac, 0x7d, 0x37, 0x6d, 0xad, 0x9f, 0xd8, 0xca,
	0xbe, 0xcb, 0xea, 0x6b, 0x56, 0xac, 0x13, 0x85, 0xba, 0xa9, 0x6c, 0x22, 0x50, 0x7c, 0xb4, 0xea,
	0x39, 0xea, 0x96, 0x2b, 0xf9, 0x1a, 0x93, 0x4f, 0xbc, 0xce, 0xb5, 0x8a, 0xc0, 0x71, 0x67, 0x7c,
	0x8d, 0xef, 0x48, 0x64, 0x2f, 0x60, 0x7f, 0xc0, 0x25, 0x15, 0xd7, 0x18, 0x8d, 0x8f, 0xbc, 0xa5,
	0x17, 0xcf, 0x7a, 0x70, 0xcc, 0x35, 0xb2, 0x67, 0x30, 0x13, 0xfc, 0x8b, 0xac, 0x7a, 0xd6, 0xbb,
	0x64, 0x1d, 0xd2, 0x46, 0xc7, 0xfc, 0x04, 0xee, 0xfe, 0xc3, 0x5a, 0xfb, 0x09, 0xd9, 0xcf, 0x07,
	0x03, 0x74, 0xc0, 0x01, 0xec, 0x14, 0xa8, 0x93, 0xea, 0x26, 0xda, 0x23, 0xd7, 0x51, 0x81, 0x3a,
	0xbe, 0x61, 0x0b, 0x98, 0x58, 0x39, 0xc1, 0xaa, 0x92, 0x95, 0x8a, 0x42, 0x7b, 0xf1, 0x68, 0xf7,
	0x2d, 0x49, 0xec, 0x39, 0xb0, 0x1e, 0x63, 0xcf, 0x9a, 0xd2, 0x59, 0x61, 0x07, 0xa4, 0x73, 0x1e,
	0xc2, 0xb8, 0x81, 0x89, 0x9a, 0x11, 0x15, 0x10, 0xd5, 0xcd, 0xa1, 0x6f, 0x22, 0xe6, 0x72, 0xac,
	0x5c, 0x0e, 0xed, 0x72, 0xcc, 0x5d, 0x8e, 0xd5, 0x20, 0x87, 0xee, 0xe7, 0xd8, 0x77, 0x39, 0x56,
	0xff, 0xc9, 0xa1, 0x9b, 0x1c, 0x07, 0x2e, 0xc7, 0x8a, 0x72, 0x2c, 0x18, 0x4c, 0xdb, 0x5b, 0xde,
	0x5e, 0xfd, 0x57, 0xbf, 0x3c, 0x98, 0x9c, 0x35, 0x8f, 0x92, 0xbd, 0xff, 0x6f, 0x60, 0x1a, 0x63,
	0x8a, 0xd9, 0x35, 0x6e, 0x5e, 0xa3, 0xe9, 0xb1, 0x7d, 0xb0, 0x9c, 0x72, 0x18, 0x0d, 0x15, 0xf7,
	0x31, 0xdd, 0x5a, 0x7a, 0x2f, 0x3d, 0x76, 0x0a, 0x61, 0xe3, 0xe2, 0x3e, 0xac, 0xb0, 0x19, 0x69,
	0x85, 0xc3, 0x7b, 0x03, 0xa1, 0x6f, 0x71, 0xb9, 0x43, 0xcf, 0xe3, 0xc9, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xeb, 0xd4, 0x75, 0x31, 0x35, 0x05, 0x00, 0x00,
}
